version: "3.7"
services:
  mongodb:
    image: mongo:6
    restart: always
    volumes:
      - mongodb_data:/data/db/
      - $PWD/logs/mongodb/:/var/log/mongodb/
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
volumes:
  mongodb_data: